[prefix]
"**/[!smithy-dafny-codegen-modules]/**/*.smithy" = """
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
"""
"**/[!smithy-dafny-codegen-modules]/**/*.java" = """
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
"""
"**/[!smithy-dafny-codegen-modules]/**/[!/obj/]*.cs" = """
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
"""
# Exclude files from dafny-lang/libraries
"**/[!Wrappers]*.dfy" = """
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
"""
"**/[!smithy-dafny-codegen-modules]/**/*.kts" = """
// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
"""
"**/[!smithy-dafny-codegen-modules]/**/*.mk" = """
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""
"**/[!smithy-dafny-codegen-modules]/**/Makefile" = """
# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""