// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleorphanedsmithygeneratedtypes

type OrphanedV1Enum string

const (
	OrphanedV1EnumFirst  OrphanedV1Enum = "0x0014"
	OrphanedV1EnumSecond OrphanedV1Enum = "0x0046"
	OrphanedV1EnumThird  OrphanedV1Enum = "0x0078"
)

func (OrphanedV1Enum) Values() []OrphanedV1Enum {
	return []OrphanedV1Enum{
		"0x0014",
		"0x0046",
		"0x0078",
	}
}
