// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleorphanedsmithygeneratedtypes

import (
	"fmt"
)

type OrphanedError struct {
	SimpleOrphanedBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e OrphanedError) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
