// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleorphanedsmithygenerated

import (
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/SimpleOrphaned"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/SimpleOrphanedTypes"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/simpleorphanedsmithygeneratedtypes"
)

type Client struct {
	DafnyClient SimpleOrphanedTypes.ISimpleOrphanedClient
}

func NewClient(clientConfig simpleorphanedsmithygeneratedtypes.SimpleOrphanedConfig) (*Client, error) {
	var dafnyConfig = SimpleOrphanedConfig_ToDafny(clientConfig)
	var dafny_response = SimpleOrphaned.Companion_Default___.SimpleOrphaned(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(SimpleOrphanedTypes.ISimpleOrphanedClient)
	client := &Client{dafnyClient}
	return client, nil
}
