[package]
name = "dafny_standard_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dafny_runtime = { path = "../../../dafny_runtime_rust"}
aws-smithy-types = "1.2.0"
