// Code generated by smithy-go-codegen DO NOT EDIT.

package WrappedSimpleOrphanedService

import (
	"context"

	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/SimpleOrphanedTypes"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/simpleorphanedsmithygenerated"
)

type Shim struct {
	SimpleOrphanedTypes.ISimpleOrphanedClient
	client *simpleorphanedsmithygenerated.Client
}

func (_static *CompanionStruct_Default___) WrappedSimpleOrphaned(inputConfig SimpleOrphanedTypes.SimpleOrphanedConfig) Wrappers.Result {
	var nativeConfig = simpleorphanedsmithygenerated.SimpleOrphanedConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = simpleorphanedsmithygenerated.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(SimpleOrphanedTypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) CreateOrphanedStructure(input SimpleOrphanedTypes.CreateOrphanedStructureInput) Wrappers.Result {
	var native_request = simpleorphanedsmithygenerated.CreateOrphanedStructureInput_FromDafny(input)
	var native_response, native_error = shim.client.CreateOrphanedStructure(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpleorphanedsmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpleorphanedsmithygenerated.CreateOrphanedStructureOutput_ToDafny(*native_response))
}

func (shim *Shim) CreateOrphanedResource(input SimpleOrphanedTypes.CreateOrphanedResourceInput) Wrappers.Result {
	var native_request = simpleorphanedsmithygenerated.CreateOrphanedResourceInput_FromDafny(input)
	var native_response, native_error = shim.client.CreateOrphanedResource(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpleorphanedsmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpleorphanedsmithygenerated.CreateOrphanedResourceOutput_ToDafny(*native_response))
}

func (shim *Shim) CreateOrphanedError(input SimpleOrphanedTypes.CreateOrphanedErrorInput) Wrappers.Result {
	var native_request = simpleorphanedsmithygenerated.CreateOrphanedErrorInput_FromDafny(input)
	var native_response, native_error = shim.client.CreateOrphanedError(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpleorphanedsmithygenerated.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpleorphanedsmithygenerated.CreateOrphanedErrorOutput_ToDafny(*native_response))
}
