// Code generated by smithy-go-codegen DO NOT EDIT.

package WrappedSimpleOrphanedService

import (
	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/SimpleOrphanedTypes"
	"github.com/smithy-lang/smithy-dafny/TestModels/OrphanedShapes/simpleorphanedsmithygenerated"
)

type Shim struct {
	SimpleOrphanedTypes.ISimpleOrphanedClient
	client *simpleorphanedsmithygenerated.Client
}

func (_static *CompanionStruct_Default___) WrappedSimpleOrphaned(inputConfig SimpleOrphanedTypes.SimpleOrphanedConfig) Wrappers.Result {
	var nativeConfig = simpleorphanedsmithygenerated.SimpleOrphanedConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = simpleorphanedsmithygenerated.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(SimpleOrphanedTypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}
