name: dafny-java-conversion workflows

on: 
  pull_request:
  push:
    branches:
      - main-1.x

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.6.1
        with:
          dafny-version: "4.0.0"

      - name: Execute tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: dafny-java-conversion
