name: dafny-java-conversion workflows

on: 
  pull_request:
  push:
    branches:
      - main-1.x

jobs:
  gradle-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "nightly-2022-12-02-edab6cc"

      # Java DafnyRuntime is not published to maven,
      # so manually download a nightly build for 3.10.0 and grab it from there.
      - name: Locally Cache Java DafnyRuntime
        run: |
          wget https://github.com/dafny-lang/dafny/releases/download/nightly/dafny-nightly-2022-12-02-edab6cc-x64-osx-10.14.2.zip 
          unzip dafny-nightly-2022-12-02-edab6cc-x64-osx-10.14.2.zip 
          mvn -B -ntp install:install-file \
          -Dfile=dafny/DafnyRuntime.jar \
          -DgroupId=dafny.lang \
          -DartifactId=DafnyRuntime \
          -Dversion=3.10.0 \
          -DgeneratePom=true \
          -Dpackaging=jar

      - name: Execute tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: dafny-java-conversion
