name: dafny-java-conversion workflows

on: 
  pull_request:
  push:
    branches:
      - main

jobs:
  gradle-build:
    strategy:
      matrix:
        dafny: [ 3.9.0 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: ${{ matrix.dafny }}
      - name: Setup dafny/DafnyRuntime.jar
        shell: bash
        run: |
          # The location of the dafny binary
          # and by extension DafnyRuntime.jar
          # should not be something that dafny-lang/setup-dafny-action
          # worries about, this works for now...
          # The `which dafny` is there to make sure they match
          which dafny
          mvn install:install-file \
          -Dfile=/opt/hostedtoolcache/dafny/${{ matrix.dafny }}/x64/DafnyRuntime.jar \
          -DgroupId=dafny.lang \
          -DartifactId=DafnyRuntime \
          -Dversion=${{ matrix.dafny }} \
          -DgeneratePom=true \
          -Dpackaging=jar
      - name: Execute tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: dafny-java-conversion
