# This workflow runs for every pull request
name: Java Format Check

on:
  pull_request:

jobs:
  check-java:
      - name: Check format of Java, md and yaml
        shell: bash
        run: |
          make format_java_misc-check
