name: smithy-dafny-codegen-cli workflows

on:
  pull_request:
  push:
    branches:
      - main-1.x

jobs:
  gradle-build-smithy-dafny:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          # Matching the hard-coded version for the "2023" edition for now
          dafny-version: 4.1.0

      - name: Execute smithy-dafny-codegen-cli tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen-cli:test
          build-root-directory: codegen

      - name: Execute smithy-dafny-codegen tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:test
          build-root-directory: codegen

      # Required for building the SQS model
      - name: Locally cache smithy-dafny-codegen
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:publishToMavenLocal
          build-root-directory: codegen

      # Required for building Smithy-Dafny
      # TODO: This step can and should be removed once Smithy-Python is on Maven central
      - name: Locally cache smithy-python-codegen
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-python-codegen:publishToMavenLocal
          build-root-directory: submodules/smithy-python/codegen

      - name: Sanity-check SQS test model via plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info
          build-root-directory: TestModels/aws-sdks/sqs

      - name: Execute codegen build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: codegen

      - name: not-grep
        if: matrix.os == 'ubuntu-latest'
        uses: mattsb42-meta/not-grep@1.0.0
