name: smithy-dafny-codegen-cli workflows

on: 
  pull_request:
  push:
    branches:
      - main-1.x

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Execute smithy-dafny-codegen-cli tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen-cli:test
          build-root-directory: codegen

      - name: Execute smithy-dafny-codegen tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:test
          build-root-directory: codegen

      # Required for building the SQS model
      - name: Locally cache smithy-dafny-codegen
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:publishToMavenLocal
          build-root-directory: codegen

      - name: Sanity-check SQS test model via plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --info
          build-root-directory: TestModels/aws-sdks/sqs

      - name: Execute codegen build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: codegen
