name: smithy-dafny-codegen-cli workflows

on: 
  pull_request:
  push:
    branches:
      - main-1.x

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1
        with:
          dafny-version: "nightly-2022-12-02-edab6cc"

      # TODO: This has been added has a workaround for https://issues.apache.org/jira/browse/MNG-7679
      # Remove this when the latest version has been patched
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: '17'
          maven-version: 3.8.7

      # Java DafnyRuntime is not published to maven,
      # so manually download a nightly build for 3.10.0 and grab it from there.
      - name: Locally Cache Java DafnyRuntime
        run: |
          wget https://github.com/dafny-lang/dafny/releases/download/nightly/dafny-nightly-2022-12-02-edab6cc-x64-ubuntu-16.04.zip
          unzip dafny-nightly-2022-12-02-edab6cc-x64-ubuntu-16.04.zip
          mvn -B -ntp install:install-file \
          -Dfile=dafny/DafnyRuntime.jar \
          -DgroupId=dafny.lang \
          -DartifactId=DafnyRuntime \
          -Dversion=3.10.0 \
          -DgeneratePom=true \
          -Dpackaging=jar

      - name: Setup dafny-java-conversion
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal
          build-root-directory: dafny-java-conversion

      - name: Execute smithy-dafny-codegen-cli tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          build-root-directory: codegen/smithy-dafny-codegen-cli

      - name: Execute smithy-dafny-codegen tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:test
          build-root-directory: codegen
