# This workflow performs tests in .NET.
name: Library net tests

on: 
  pull_request:
  push:

jobs:
  testDotNet:
    strategy:
      matrix:
        testSuite: [
          smithy-polymorph-tests/dependencies/StandardLibrary, # This stores current Polymorph dependencies that all tests depend on
        ]
        os: [ ubuntu-latest ] 
        dotnet-version: [ '6.0.x' ]
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.4.0
        with:
          dafny-version: "3.10.0"

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Download Dependencies 
        working-directory: ./${{ matrix.testSuite }}
        run: make setup_net

      - name: Compile TestSuite implementation
        shell: bash
        working-directory: ./${{ matrix.testSuite }}
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make transpile_net CORES=$CORES

      - name: Test ${{ matrix.testSuite }}
        working-directory: ./${{ matrix.testSuite }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            make test_net_mac_intel
          else
            make test_net
          fi
