# This workflow performs tests in .NET.
name: Library net tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  testDotNet:
    strategy:
      fail-fast: false
      matrix:
        dafny-version:
          - ${{ inputs.dafny }}
        shard: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
        dotnet-version: ["6.0.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-PolymorphTestModels-Role-us-west-2
          role-session-name: NetTests

      - uses: actions/checkout@v3

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ matrix.dafny-version }}

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # GitHub's docs on problem matcher's ::
      # https://github.com/actions/toolkit/blob/master/docs/commands.md#problem-matchers
      - name: Disable setup-dotnet's problem matcher
        # setup-dotnet's problem matcher:
        # https://github.com/actions/setup-dotnet/blob/main/.github/csc.json
        run: echo "::remove-matcher owner=csc::"

      - name: Setup Java 17 for codegen
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Execute smithy-dafny-codegen-test tests
        uses: gradle/gradle-build-action@v2
        env:
          JUNIT_SHARD: ${{ matrix.shard }}
          JUNIT_SHARD_COUNT: 10
        with:
          arguments: :smithy-dafny-codegen-test:test --tests '*smithydotnet*' --info
          build-root-directory: codegen
