# This workflow runs polymorph_code_gen.
name: polymorph_code_gen test

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  testPolymorphCodeGen:
    runs-on: "ubuntu-latest"
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ inputs.dafny }}

      - name: Setup Java 17 for codegen
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup Python for running tests
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade tox
          pip install poetry

      - name: Install Python formatters
        run: make setup_smithy_dafny_python

      - name: Build one TestModel with all languages (smoke test for polymorph_code_gen target)
        shell: bash
        working-directory: TestModels/SimpleTypes/SimpleString
        run: make polymorph_code_gen
