# This workflow formally verifies the generated Dafny.
name: Library Dafny verification

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  verification:
    strategy:
      fail-fast: false
      matrix:
        dafny-version:
          - ${{ inputs.dafny }}
        library: [
            TestModels/dafny-dependencies/StandardLibrary, # This stores current Polymorph dependencies that all TestModels depend on
            TestModels/Aggregate,
            TestModels/AggregateReferences,
            TestModels/CodegenPatches,
            TestModels/Constraints,
            TestModels/Constructor,
            TestModels/Dependencies,
            TestModels/Errors,
            TestModels/Extendable,
            TestModels/Extern,
            # TestModels/LanguageSpecificLogic, # requires >4.4.0
            TestModels/LocalService,
            TestModels/MultipleModels,
            TestModels/Refinement,
            TestModels/Resource,
            # TestModels/SimpleTypes/BigDecimal,
            # TestModels/SimpleTypes/BigInteger,
            TestModels/SimpleTypes/SimpleBlob,
            TestModels/SimpleTypes/SimpleBoolean,
            # TestModels/SimpleTypes/SimpleByte,
            TestModels/SimpleTypes/SimpleDouble,
            TestModels/SimpleTypes/SimpleEnum,
            # TestModels/SimpleTypes/SimpleEnumV2,
            # TestModels/SimpleTypes/SimpleFloat,
            TestModels/SimpleTypes/SimpleInteger,
            TestModels/SimpleTypes/SimpleLong,
            # TestModels/SimpleTypes/SimpleShort,
            TestModels/SimpleTypes/SimpleString,
            # TestModels/SimpleTypes/SimpleTimestamp,
            TestModels/Union,
            TestModels/aws-sdks/ddb,
            TestModels/aws-sdks/kms,
            TestModels/aws-sdks/sqs-via-cli,
          ]
        os: [ubuntu-latest]
        include:
          # One-offs until TestModels migrate to 4.4.0
          - library: TestModels/LanguageSpecificLogic
            dafny-version: 4.4.0
            os: ubuntu-latest
          - library: TestModels/Extendable
            dafny-version: 4.4.0
            os: ubuntu-latest
        exclude:
          # This model tickles a tricky Dafny verification regression fixed in 4.4
          # https://github.com/dafny-lang/dafny/pull/4800
          - dafny-version: 4.2.0
            library: TestModels/Extendable
          - dafny-version: 4.3.0
            library: TestModels/Extendable
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths
        run: |
          git config --global core.longpaths true

      - uses: actions/checkout@v2

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ matrix.dafny-version }}

      - name: Generate Polymorph Wrapper Dafny code
        working-directory: ./${{ matrix.library }}
        run: |
          make polymorph_dafny DAFNY_VERSION_OPTION="--dafny-version $DAFNY_VERSION"

      - name: Verify ${{ matrix.library }} Dafny code
        working-directory: ./${{ matrix.library }}
        run: |
          # This works because `node` is installed by default on GHA runners
          CORES=$(node -e 'console.log(os.cpus().length)')
          make verify CORES=$CORES

      - name: Check solver resource use
        working-directory: ./${{ matrix.library }}
        run: |
          make dafny-reportgenerator
