# This workflow performs tests in Java.
name: Library Java tests

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string

jobs:
  testJava:
    strategy:
      fail-fast: false
      matrix:
        shard: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths on Git checkout
        run: |
          git config --global core.longpaths true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-PolymorphTestModels-Role-us-west-2
          role-session-name: JavaTests

      - uses: actions/checkout@v3

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ inputs.dafny }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Setup smithy-dafny-conversion
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToMavenLocal
          build-root-directory: smithy-dafny-conversion

      - name: Execute smithy-dafny-codegen-test tests
        uses: gradle/gradle-build-action@v2
        env:
          JUNIT_SHARD: ${{ matrix.shard }}
          JUNIT_SHARD_COUNT: 10
        with:
          arguments: :smithy-dafny-codegen-test:test --tests '*smithyjava*'
          build-root-directory: codegen
