# This workflow formally verifies the generated Dafny.
name: Library Dafny verification

on:
  workflow_call:
    inputs:
      dafny:
        description: "The Dafny version to run"
        required: true
        type: string
      num_shards:
        required: false
        type: number
        default: 10

jobs:
  populate-matrix-dimensions:
    runs-on: ubuntu-latest
    steps:
      - name: Populate shard list
        id: populate-shard-list
        run: echo "shard-list=[`seq -s , 1 ${{ inputs.num_shards }}`]" >> $GITHUB_OUTPUT
    outputs:
      shard-list: ${{ steps.populate-shard-list.outputs.shard-list }}
  verification:
    needs: populate-matrix-dimensions
    strategy:
      fail-fast: false
      matrix:
        dafny-version:
          - ${{ inputs.dafny }}
        shard: ${{ fromJson(needs.populate-matrix-dimensions.outputs.shard-list) }}
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - name: Support longpaths
        run: |
          git config --global core.longpaths true

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Dafny
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: ${{ matrix.dafny-version }}

      - name: Setup Java 17 for codegen
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Install smithy-dafny-codegen dependencies locally
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :codegen-client:pTML :codegen-core:pTML :rust-runtime:pTML
          build-root-directory: smithy-dafny-codegen-modules/smithy-rs

      - name: Install smithy-dafny-codegen locally
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :smithy-dafny-codegen:pTML
          build-root-directory: codegen

      - name: Execute smithy-dafny-codegen-test tests
        uses: gradle/gradle-build-action@v2
        env:
          JUNIT_SHARD: ${{ matrix.shard }}
          JUNIT_SHARD_COUNT: ${{ inputs.num_shards }}
        with:
          arguments: :smithy-dafny-codegen-test:test --tests '*smithydafny*' --info
          build-root-directory: codegen
